import { buildEditableLectureHtml } from "./editable-lecture-html.js";

const $=(s)=>document.querySelector(s);const text=$("#lectureText"),file=$("#textFile"),status=$("#status"),preview=$("#preview"),download=$("#downloadHtml"),open=$("#openWindow"),title=$("#previewTitle");let result=null;
function setStatus(message,error=false){status.textContent=message;status.style.color=error?"#922b21":"#3a3a38";}
file.addEventListener("change",async()=>{const selected=file.files?.[0];if(!selected)return;if(!/\.txt$/i.test(selected.name)&&selected.type!=="text/plain"){setStatus("Only UTF-8 text files are accepted.",true);return;}try{text.value=await selected.text();setStatus(`Imported ${selected.name}. It will use the same parser as pasted text.`);}catch(error){setStatus(error.message||"The text file could not be read.",true);}});
$("#clearText").addEventListener("click",()=>{text.value="";result=null;preview.removeAttribute("srcdoc");download.disabled=true;open.disabled=true;setStatus("");});
$("#buildHtml").addEventListener("click",()=>{try{if(!text.value)throw new Error("Paste lecture text or import a .txt file first.");result=buildEditableLectureHtml(text.value,{courseCode:$("#courseCode").value,lectureLabel:$("#lectureLabel").value,instructor:$("#instructor").value});preview.srcdoc=result.html;download.disabled=false;open.disabled=false;title.textContent=`Preview · ${result.document.blocks.length} source blocks`;setStatus(`Verified ${result.verification.rendered} rendered source blocks. No source block was missing or duplicated.`);}catch(error){result=null;download.disabled=true;open.disabled=true;setStatus(error.message||"The lecture could not be built.",true);}});
download.addEventListener("click",()=>{if(!result)return;const blob=new Blob([result.html],{type:"text/html;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=result.filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
open.addEventListener("click",()=>{if(!result)return;const win=window.open("","_blank");if(!win){setStatus("The browser blocked the editor window.",true);return;}win.document.open();win.document.write(result.html);win.document.close();});
